version: '3'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports: 
      - "443:443"
    restart: always
    volumes:
      - wordpress:/var/www/html
  mariadb:
    container_name: mariadb
    restart: always
    ports:
      -